---
- name: Install the selinux python module
  package: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
    - policycoreutils-python
  tags:
    - cachet
    - cachet-selinux

- name: "Set up context on install dir"
  sefcontext:
    target: "{{ cachet_install_dir }}(/.*)?"
    setype: httpd_sys_rw_content_t
  with_items:
    - "{{ cachet_install_dir }}(/.*)?"
    - "{{ cachet_install_dir }}/bootstrap(/.*)?"
  tags:
    - cachet
    - cachet-selinux

- name: "Allow php-fpm to bind to listener socket on port {{ cachet_php_fpm_listen_port }}"
  seport:
    ports: "{{ cachet_php_fpm_listen_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  when: cachet_install_php
  tags:
    - cachet
    - cachet-selinux

- name: Toggles required SElinux booleans
  seboolean:
    name: "{{ item }}"
    persistent: yes
    state: yes
  with_items:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - httpd_read_user_content
    - httpd_execmem
  tags:
    - cachet
    - cachet-selinux

- name: Restore context on install dir
  command: "restorecon -R -v {{ cachet_install_dir }}"
  tags:
    - cachet
    - cachet-selinux
