---
- name: Clear cache
  command: php artisan '{{ item }}'
  args:
    chdir: '{{ cachet_install_dir }}'
  become: yes
  become_user: '{{ cachet_user }}'
  with_items:
    - cache:clear
    - config:cache

- name: Restart php-fpm
  service:
    name: php-fpm
    state: restarted
  when: cachet_install_php
